version: '3'

services:
  bridge:
    build:
      context: .
    # If you have devices connected to the relay, add them here
    # devices:
      # - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/serial:/dev/serial"
    runtime: sysbox-runc
    ports:
      - 5000:8080
