# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/observing.ipynb.
from components.device import get_device_port

# %% auto 0
__all__ = ['read_person_detection_from_serial']

# %% ../nbs/observing.ipynb 1
from serial import Serial

# %% ../nbs/observing.ipynb 2
def read_person_detection_from_serial(serial:str):
    "Reads a single person detection prediction line over serial and returns dict containing scores with keys `Person` and `No person`. Returns None if serial fails."
    
    port = get_device_port(serial)
    
    try:
        with Serial(port, baudrate=19200, timeout=1) as ser:
            output = ser.readline().decode("ascii").strip() # "Person score: 60.54% No person score: 39.45%"
            parts = output.split(" ")
            print(parts)
            return parts#{"Person":float(parts[2][:-1]), "No person":float(parts[6][:-1])}
    except Exception as e:
        print(e)
        return None
    
    return Nonde

read_person_detection_from_serial("D2AFB75328FD1996")