# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/observing.ipynb.
from .components.device import get_device_port

# %% auto 0
__all__ = ['read_prediction_from_port']

# %% ../nbs/observing.ipynb 1
from serial import Serial

# %% ../nbs/observing.ipynb 2
def read_prediction_from_port(port:str):
    "Reads a single person detection prediction line over serial and returns dict containing scores with keys `Person` and `No person`. Returns None if serial fails."

    #port = get_device_port(serial)

    try:
        with Serial(port, baudrate=19200, timeout=1) as ser:
            output = ser.readline().decode("ascii").strip() # "Person score: 60.54% No person score: 39.45%"
            parts = output.split(" ")

            return {"1":float(parts[2][:-1]), "0":float(parts[6][:-1])}

    except Exception as the_exception:
        print(the_exception)
        
        return None

